name: Terraform Apply(Manual)

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_ver: ${{ vars.ver }}
  TF_VAR_docker_compose_bucket_name: ${{ vars.S3_PATH_TO_COMPOSE_FILE }}
  TF_VAR_private_key_path: ${{ secrets.PRIVATE_KEY_PATH }}
  TF_VAR_key_name: ${{ secrets.KEY_NAME }}
  TF_VAR_postgres_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_access_token_salt: ${{ secrets.ACCESS_TOKEN_SALT }}
  TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
  TF_VAR_redis_password: ${{ secrets.REDIS_PASSWORD }}


on:
  workflow_dispatch:

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init

    - name: Set up SSH private key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem     

    - name: Terraform Apply
      run: terraform apply -auto-approve

